import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillGithub, AiFillLinkedin, AiFillYoutube} from 'react-icons/ai'
import Image from "next/image";
import memoji from '../public/memoji.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import proj1 from "../public/proj1.jpeg";
import proj2 from "../public/proj2.png";
import proj3 from "../public/proj3.png";
import proj4 from "../public/proj4.jpeg";
import proj5 from "../public/proj5.jpeg";
import proj6 from "../public/proj6.png";
import {useState} from "react"

import Link from 'next/link'


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Carlo Cortez Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between ">
            <Link href="/">
              <h1 className="text-xl font-burtons dark:text-white">Carlo Cortez</h1> 
            </Link>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)}
                  className='cursor-pointer text-2xl'/>
              </li>
              <li>
                <Link href="/about" 
                      className="bg-gradient-to-r from-sky-400 to-blue-500 text-white px-2 py-2 rounded-md ml-5"> 
                      About
                </Link>
              </li>
              <li>
              <Link className="bg-gradient-to-r from-sky-400 to-blue-500 text-white px-2 py-2 rounded-md ml-5" 
                      href="https://drive.google.com/file/d/1Rqenhch-imU5_QvPmgIGj3d7ZGwnviQ8/view?usp=sharing">
                      Resume
                </Link>
              </li>
            </ul>
          </nav>
          <div className='text-center p-10 dark:text-white'>
            <h2 className="text-5xl py-2 text-blue-500 font-medium md:text-6xl"> Hi! I am Carlo Cortez</h2>
            <h3 className='text-2xl py-2 md:text-3xl'> Developer and designer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-white'> A student that creates projects related to programming and UI design</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <a href="https://github.com/Cotrii">
              <AiFillGithub />
            </a>
            
            <a href="https://www.linkedin.com/in/carlo-miguel-cortez-27454a1a7/">
             <AiFillLinkedin/>
            </a>
            <a href="https://github.com/carlocortez">
              <AiFillGithub color='green' />
            </a>
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-blue-300 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
            <Image src={memoji}  layout='fill' objectFit="cover"/>
          </div>
        </section>
        
        <section>
          <div>
            <h3 className="text-3xl py-2 dark:text-white">Services I offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
              Since the beginning of my journey as a student developer, I have done multiple projects related to
              <span className='text-blue-500'> web development</span>  and <span className='text-blue-500'>UX Design</span> 
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image className='mx-auto' src={design} width="100" height="100"></Image>
              <h3 className='text-lg font-medium pt-8 pb-2'> Designs</h3>
              <p className="py-2"> Creating minimal designs</p>
              <h4 className="py-4 text-blue-500"> Design tools used</h4>
              <p className='text-gray-800 py-1'> Figma </p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image className='mx-auto' src={code} width="100" height="100"></Image>
              <h3 className='text-lg font-medium pt-8 pb-2'> Code </h3>
              <p className="py-2"> Creating applications </p>
              <h4 className="py-4 text-blue-500"> Programming languages learned</h4>
              <p className='text-gray-800 py-1'> Java </p>
              <p className='text-gray-800 py-1'> Python </p>
              <p className='text-gray-800 py-1'> Javascript </p>
              <p className='text-gray-800 py-1'> C </p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
            <Image className='mx-auto' src={consulting} width="100" height="100"></Image>
              <h3 className='text-lg font-medium pt-8 pb-2'> Analysis </h3>
              <p className="py-2"> Displaying visuals and tables </p>
              <h4 className="py-4 text-blue-500"> Tools used</h4>
              <p className='text-gray-800 py-1'> SQL </p>
              <p className='text-gray-800 py-1'> PowerBI </p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-white'> Portfolio </h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
            Here are some projects that I have worked on over the past few years. The first portion is related to UX/UI Design, coming from design challenges or case studies. One of the projects got translated into code as it was just a simple UI.
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'><Image src={proj1} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/></div>
            <div className='basis-1/3 flex-1'><Image src={proj2} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/></div>
            <div className='basis-1/3 flex-1'><Image src={proj3} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/></div>
            <div className='basis-1/3 flex-1'><Image src={proj4} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/></div>
          </div>
          <div>
            <h3 className='text-3xl py-1 dark:text-white'> Programming Projects </h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
            Related to web programming, here are my two most recent projects. PCGuro&rsquo;s goal was to create a community forum on local shops
            here in the Philippines so that we can avoid using websites like PCPartPicker for prices and builds. The other project was a case study related to inventory management for a company. 
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'><Image src={proj5} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/></div>
            <div className='basis-1/3 flex-1'><Image src={proj6} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/></div>
          </div>
        </section>
      </main>
    </div>
  )
}
